/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/rgb/examples/HelloEverythingSomeIPDeployment.hpp>

namespace v1 {
namespace rgb {
namespace examples {
namespace HelloEverything_ {

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace HelloEverything_
} // namespace examples
} // namespace rgb
} // namespace v1
