/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_RGB_EXAMPLES_Hello_Everything_PROXY_BASE_HPP_
#define V1_RGB_EXAMPLES_Hello_Everything_PROXY_BASE_HPP_

#include <v1/rgb/examples/HelloEverything.hpp>


#include <v1/rgb/examples/MyTypes.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>

#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Proxy.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace rgb {
namespace examples {

class HelloEverythingProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::ObservableAttribute<int32_t> MyTestAttributeAttribute;
    typedef CommonAPI::ObservableAttribute<::v1::rgb::examples::MyTypes::MyStruct> MyCustomTestAttributeAttribute;


    virtual MyTestAttributeAttribute& getMyTestAttributeAttribute() = 0;
    virtual MyCustomTestAttributeAttribute& getMyCustomTestAttributeAttribute() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace examples
} // namespace rgb
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_RGB_EXAMPLES_Hello_Everything_PROXY_BASE_HPP_
