/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/rgb/examples/HelloEverythingSomeIPStubAdapter.hpp>
#include <v1/rgb/examples/HelloEverything.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace rgb {
namespace examples {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createHelloEverythingSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< HelloEverythingSomeIPStubAdapter<::v1::rgb::examples::HelloEverythingStub>>(_address, _connection, _stub);
}

void initializeHelloEverythingSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:rgb.examples.HelloEverything:v1_0:rgb.examples.HelloEverythingInstance0",
         0x1234, 0x5678, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "rgb.examples.HelloEverything:v1_0",
        &createHelloEverythingSomeIPStubAdapter);
}

INITIALIZER(registerHelloEverythingSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeHelloEverythingSomeIPStubAdapter);
}

} // namespace examples
} // namespace rgb
} // namespace v1
