/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_RGB_EXAMPLES_Hello_Everything_STUB_DEFAULT_HPP_
#define V1_RGB_EXAMPLES_Hello_Everything_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/rgb/examples/HelloEverythingStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace rgb {
namespace examples {

/**
 * Provides a default implementation for HelloEverythingStubRemoteEvent and
 * HelloEverythingStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT HelloEverythingStubDefault
    : public virtual HelloEverythingStub {
public:
    COMMONAPI_EXPORT HelloEverythingStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(HelloEverything::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT HelloEverythingStubRemoteEvent* initStubAdapter(const std::shared_ptr< HelloEverythingStubAdapter> &_adapter) {
        CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual const int32_t &getMyTestAttributeAttribute() {
        return myTestAttributeAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const int32_t &getMyTestAttributeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getMyTestAttributeAttribute();
    }
    COMMONAPI_EXPORT virtual void setMyTestAttributeAttribute(int32_t _value) {
        const bool valueChanged = trySetMyTestAttributeAttribute(std::move(_value));
        if (valueChanged) {
            fireMyTestAttributeAttributeChanged(myTestAttributeAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void setMyTestAttributeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _value) {
        (void)_client;
        setMyTestAttributeAttribute(_value);
    }
    COMMONAPI_EXPORT virtual const ::v1::rgb::examples::MyTypes::MyStruct &getMyCustomTestAttributeAttribute() {
        return myCustomTestAttributeAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const ::v1::rgb::examples::MyTypes::MyStruct &getMyCustomTestAttributeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getMyCustomTestAttributeAttribute();
    }
    COMMONAPI_EXPORT virtual void setMyCustomTestAttributeAttribute(::v1::rgb::examples::MyTypes::MyStruct _value) {
        const bool valueChanged = trySetMyCustomTestAttributeAttribute(std::move(_value));
        if (valueChanged) {
            fireMyCustomTestAttributeAttributeChanged(myCustomTestAttributeAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void setMyCustomTestAttributeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::rgb::examples::MyTypes::MyStruct _value) {
        (void)_client;
        setMyCustomTestAttributeAttribute(_value);
    }


protected:
    COMMONAPI_EXPORT virtual bool trySetMyTestAttributeAttribute(int32_t _value) {
        if (!validateMyTestAttributeAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<HelloEverythingStubAdapter> stubAdapter = CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockMyTestAttributeAttribute(true);
            valueChanged = (myTestAttributeAttributeValue_ != _value);
            myTestAttributeAttributeValue_ = std::move(_value);
            stubAdapter->lockMyTestAttributeAttribute(false);
        } else {
            valueChanged = (myTestAttributeAttributeValue_ != _value);
            myTestAttributeAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateMyTestAttributeAttributeRequestedValue(const int32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual void onRemoteMyTestAttributeAttributeChanged() {
        // No operation in default
    }
    COMMONAPI_EXPORT virtual bool trySetMyCustomTestAttributeAttribute(::v1::rgb::examples::MyTypes::MyStruct _value) {
        if (!validateMyCustomTestAttributeAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<HelloEverythingStubAdapter> stubAdapter = CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockMyCustomTestAttributeAttribute(true);
            valueChanged = (myCustomTestAttributeAttributeValue_ != _value);
            myCustomTestAttributeAttributeValue_ = std::move(_value);
            stubAdapter->lockMyCustomTestAttributeAttribute(false);
        } else {
            valueChanged = (myCustomTestAttributeAttributeValue_ != _value);
            myCustomTestAttributeAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateMyCustomTestAttributeAttributeRequestedValue(const ::v1::rgb::examples::MyTypes::MyStruct &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual void onRemoteMyCustomTestAttributeAttributeChanged() {
        // No operation in default
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual HelloEverythingStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(HelloEverythingStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }

        COMMONAPI_EXPORT virtual void onRemoteMyTestAttributeAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteMyTestAttributeAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetMyTestAttributeAttribute(int32_t _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetMyTestAttributeAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetMyTestAttributeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _value) {
            (void)_client;
            return onRemoteSetMyTestAttributeAttribute(_value);
        }
        COMMONAPI_EXPORT virtual void onRemoteMyCustomTestAttributeAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteMyCustomTestAttributeAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetMyCustomTestAttributeAttribute(::v1::rgb::examples::MyTypes::MyStruct _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetMyCustomTestAttributeAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetMyCustomTestAttributeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::rgb::examples::MyTypes::MyStruct _value) {
            (void)_client;
            return onRemoteSetMyCustomTestAttributeAttribute(_value);
        }

    private:
        HelloEverythingStubDefault *defaultStub_;
    };
protected:
    HelloEverythingStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    int32_t myTestAttributeAttributeValue_ {};
    ::v1::rgb::examples::MyTypes::MyStruct myCustomTestAttributeAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace examples
} // namespace rgb
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_RGB_EXAMPLES_Hello_Everything_STUB_DEFAULT
