/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_EXAMPLES_HELLO_WORLD_INSTANCE_HPP_
#define V0_COMMONAPI_EXAMPLES_HELLO_WORLD_INSTANCE_HPP_

#include <string>

namespace v0 {
namespace commonapi {
namespace examples {

const char * const HelloWorld_commonapi_examples_HelloWorld = "commonapi.examples.HelloWorld";

const std::string HelloWorld_INSTANCES[] = {
    HelloWorld_commonapi_examples_HelloWorld
};

} // namespace examples
} // namespace commonapi
} // namespace v0

// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_EXAMPLES_HELLO_WORLD_INSTANCE_HPP_
