/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_RGB_EXAMPLES_Hello_Everything_STUB_HPP_
#define V1_RGB_EXAMPLES_Hello_Everything_STUB_HPP_

#include <functional>
#include <sstream>



#include <v1/rgb/examples/MyTypes.hpp>

#include <v1/rgb/examples/HelloEverything.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace rgb {
namespace examples {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service HelloEverything. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class HelloEverythingStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual HelloEverything {
 public:
    ///Notifies all remote listeners about a change of value of the attribute MyTestAttribute.
    virtual void fireMyTestAttributeAttributeChanged(const int32_t &MyTestAttribute) = 0;
    ///Notifies all remote listeners about a change of value of the attribute MyCustomTestAttribute.
    virtual void fireMyCustomTestAttributeAttributeChanged(const ::v1::rgb::examples::MyTypes::MyStruct &MyCustomTestAttribute) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockMyTestAttributeAttribute(bool _lockAccess) {
        if (_lockAccess) {
            myTestAttributeMutex_.lock();
        } else {
            myTestAttributeMutex_.unlock();
        }
    }
    void lockMyCustomTestAttributeAttribute(bool _lockAccess) {
        if (_lockAccess) {
            myCustomTestAttributeMutex_.lock();
        } else {
            myCustomTestAttributeMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex myTestAttributeMutex_;
    std::recursive_mutex myCustomTestAttributeMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for HelloEverything.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class HelloEverythingStubRemoteEvent
{
public:
    virtual ~HelloEverythingStubRemoteEvent() { }

    /// Verification callback for remote set requests on the attribute MyTestAttribute
    virtual bool onRemoteSetMyTestAttributeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _value) = 0;
    /// Action callback for remote set requests on the attribute MyTestAttribute
    virtual void onRemoteMyTestAttributeAttributeChanged() = 0;
    /// Verification callback for remote set requests on the attribute MyCustomTestAttribute
    virtual bool onRemoteSetMyCustomTestAttributeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::rgb::examples::MyTypes::MyStruct _value) = 0;
    /// Action callback for remote set requests on the attribute MyCustomTestAttribute
    virtual void onRemoteMyCustomTestAttributeAttributeChanged() = 0;
};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service HelloEverything to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class HelloEverythingStub
    : public virtual CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>
{
public:

    virtual ~HelloEverythingStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 2);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Provides getter access to the attribute MyTestAttribute
    virtual const int32_t &getMyTestAttributeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireMyTestAttributeAttributeChanged(int32_t _value) {
    auto stubAdapter = CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireMyTestAttributeAttributeChanged(_value);
    }
    void lockMyTestAttributeAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockMyTestAttributeAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute MyCustomTestAttribute
    virtual const ::v1::rgb::examples::MyTypes::MyStruct &getMyCustomTestAttributeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireMyCustomTestAttributeAttributeChanged(::v1::rgb::examples::MyTypes::MyStruct _value) {
    auto stubAdapter = CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireMyCustomTestAttributeAttributeChanged(_value);
    }
    void lockMyCustomTestAttributeAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockMyCustomTestAttributeAttribute(_lockAccess);
    }


    using CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<HelloEverythingStubAdapter, HelloEverythingStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef HelloEverythingStubRemoteEvent RemoteEventType;
    typedef ::v1::rgb::examples::HelloEverything StubInterface;
};

} // namespace examples
} // namespace rgb
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_RGB_EXAMPLES_Hello_Everything_STUB_HPP_
